### ISSUE TITLE
开源项目要注意隐私数据

### ISSUE THREAD

**Issue by Nick233333** [chenjun1127/vue-mall#1]
mail.config.js 文件的邮箱密码没删除，建议用 `dotenv` 管理配置

**Comment by chenjun1127** [comment]
这个没有注意，感谢，已屏蔽

**Comment by Nick233333** [comment]
不客气，正在观摩你的代码，无意间发现。。。

**Comment by hellozimo** [comment]
@chenjun1127 mail.config.js 中的邮箱和密码依旧保存在 Git 的 commit 记录里，建议重新检出提交，或者修改邮箱的密码。（建议及时修改密码）
